ORMAT: 1A
HOST: http://polls.apiblueprint.org/

# rosca-api

Road Scan App API definition

# Group Gps
Group of all gps related resources.

## GPS status [/api/gps/status]

### Get gps serial port status [GET]

+ Response 200 (application/json; charset=utf-8)

        {
          "payload" : {
             "status": "gps:off",
             "isPortOpen": false,
             "ggs": {
               "status": "",
               "messages": "",
             }
           }
        }