swagger: '2.0'
info:
  version: '1.0'
  title: "Road Scan App"
  description: Application for road scanning
  license:
    name: MIT
    url: https://github.com/apiaryio/polls-api/blob/master/LICENSE
host: polls.apiblueprint.org
basePath: /
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /api/gps/status:
    x-summary: Status of gps serial port
    get:
      summary: Get status
      responses:
        200:
          description: Successful Response
          schema:
            type: object
          examples:
            application/json:
              - payload: 
                - status: 'gps:off'
                  isPortOpen: false
                  ggs:
                  - status: ''
                    messages: ''